version: '3'

services:
  monitoringnetcore:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7009:7009"
      - "5273:5273"
    depends_on:
      - minio
      - postgres
      - video_processor
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "monitoring"
      AWS_ENDPOINT: "http://minio:9000"
      AWS_ACCESS_KEY_ID: minioaccesskey
      AWS_SECRET_ACCESS_KEY_ID: miniosecretkey
      VIDEO_PROCESSOR_SERVICE_URL: "http://video_processor:8000"
      ASPNETCORE_URLS: "http://*:5273"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitoring
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    ports:
      - "9000:9000"
      - "9001:9001"
    
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioaccesskey miniosecretkey;
      /usr/bin/mc mb myminio/uploads;
      /usr/bin/mc anonymous set public myminio/uploads;
      /usr/bin/mc mb myminio/thumbnails;
      /usr/bin/mc anonymous set public myminio/thumbnails;
      exit 0;
      "

  video_processor:
    build:
      context: ./video_processor  # path to your Python Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  db_data: {}
  minio_data: {}

